version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    DW_HOST: dw-postgres
    DW_PORT: 5432
    DW_DB: datawarehouse
    DW_USER: dw_user
    DW_PASSWORD: dw_password
    DBT_PROFILES_DIR: /opt/airflow/include/dbt_project
    DBT_ALLOW_EXPERIMENTAL_ADAPTERS: "true"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./include:/opt/airflow/include
    - ./logs:/opt/airflow/logs
  depends_on:
    - airflow-db
    - dw-postgres

services:
  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-db-data:/var/lib/postgresql/data

  dw-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password
      POSTGRES_DB: datawarehouse
    ports:
      - "5433:5432"
    volumes:
      - dw-postgres-data:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init

  dashboard:
    build:
      context: ./dashboard
    environment:
      DW_HOST: dw-postgres
      DW_PORT: 5432
      DW_DB: datawarehouse
      DW_USER: dw_user
      DW_PASSWORD: dw_password
    ports:
      - "8502:8501"
    depends_on:
      - dw-postgres

volumes:
  airflow-db-data:
  dw-postgres-data: